export const routes = {
    ProfilePage: '/profile/id/:id',
    LoginPage: '/login',
    RecoverPage: '/recover-password',
    ResetPage: '/reset-password',
    ResetNoFoundPage: '/reset-password/*',
    RecordPage: '/record-management',
    EditRecord: '/record/edit/:id',
    ApproveRecord: '/approve-record',
    Entrustment: '/entrustment-contract',
    ETMContractDetail: '/contract-detail/:id',
    AddETMContract: '/contract-detail/add',
    ETMContractCopy: '/entrustment-contract/copy/:id',
    PlaylistManagement: '/playlist-management',
    PlaylistDetail: '/playlist-detail/:id',
    EditPlaylistDetail: '/playlist-detail/edit/:id',
    AddPlaylist: '/playlist/add',
    AddRecordPlaylist: '/playlist-detail/:id/add-record',
    PlaylistSchedule: '/playlist-schedule',
    PlaylistScheduleDetail: '/playlist-schedule/detail/:id',
    PlaylistScheduleEdit: '/playlist-schedule/detail/edit/:id',
    ApplySchedule: '/playlist-schedule/detail/edit/:id/apply-schedule',
    AddPlaylistSchedule: '/playlist-schedule/add',
    Unit: '/unit/management',
    AuthorizedContract: '/authorized-contract-management',
}